export const ROUTES = {
  PING: '/ping',
  SIGN_UP: '/signup',
  LOGIN: '/login',
  REFRESH_TOKEN: '/refresh',
  HEP: '/v1/hep/fetch',
  GNS: '/v1/gns/fetch',
  POLICY: '/v1/policy/fetch',
  FETCH_OPTIONS: '/v1/options/fetch',
  SEARCH_HEP: '/v1/hep/search',
  SEARCH_GNS: '/v1/gns/search',
  SEARCH_POLICY: '/v1/policy/search',
  STATISTIC: '/v1/statistic/summary',
  PROJECT_STATISTIC: '/v1/statistic/project-summary',
  GET_USERS: '/v1/admin/user/fetch',
  PROFILE: '/v1/profile',
  CREATE_USER: '/v1/admin/user/create',
  DELETE_USER: '/v1/admin/user/delete',
  UPDATE_USER: '/v1/admin/user/update',
  UPDATE_CURRENT_USER: '/v1/profile/update',
};
